test_add_two_zhengshu (python_api.unit_test.test) ... ok
test_jianfa_zhengshu (python_api.unit_test.test) ... FAIL

======================================================================
FAIL: test_jianfa_zhengshu (python_api.unit_test.test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\python_auto\python_api\unit_test.py", line 26, in test_jianfa_zhengshu
    self.assertEqual(4,res,'两个数相减出错了')
AssertionError: 4 != 3 : 两个数相减出错了

----------------------------------------------------------------------
Ran 2 tests in 0.002s

FAILED (failures=1)
